# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/mcmpdemo # Ex: us.icr.io/mynamespace
  pullPolicy: Always
  pullSecret: ""

ingress:
  enabled: true
  hosts:
    - jpetstore.<Ingress Subdomain> # Ex: jpetstore.myclustername.us-south.containers.appdomain.cloud 